### ISSUE TITLE
hdfs-nfs-proxy can not append file...

### ISSUE THREAD

**Issue by jeffery9** [brockn/hdfs-nfs-proxy#5] opened 2012-02-03 06:50 UTC
this is a great software. but there i surface some problem,

1, it seemed not support append feature.
2, the user UID mapping is a magical thing, can let user customize the mapping thing? 
eg,  i have run hdfs-nfs-proxy  with hadoop user,,, but on another host, i need use root to mount the nfs export, and hadoop authorize system not let me mount because,, mount.nfs send root UID/GID to hdfs-nfs-proxy, and hdfs-nfs-proxy use system  /etc/passwd  /etc/group to find the user name ,,,,, forward this to hadoop , and not match with hadoop user.

**Comment by brockn** [comment] 2012-02-03 20:23
1) Append will not be supported until there is a 0.23 branch of hadoop ready for production use.

2) Can you post the log file in a gist of when this occurs?

**Comment by nickb937** [comment] 2012-02-16 12:58
Here's an example of point 2:

I run all hadoop daemons as user 'nickb' and the hdfs-nfs-proxy is also running as user 'nickb'.

On client machine:

/etc/fstab:
192.168.1.2:/ /export/hdfs nfs4       rw,owner,user,noauto,port=2050,intr,timeo=600      0 0

nickb@satellite:/export$ mount /export/hdfs 
mount.nfs4: Remote I/O error
nickb@satellite:/export$ 

Error logs from hdfs-nfs-proxy:

12/02/16 12:54:43 INFO rpc.ClientWorker: Got SecurityHandler of type com.cloudera.hadoop.hdfs.nfs.security.SecurityHandler
12/02/16 12:54:43 INFO rpc.ClientWorker: 0x7fffffb9 got request
12/02/16 12:54:43 INFO rpc.ClientWorker: 0x7fffffb9 Handling NFS NULL Procedure for satellite.local:715
12/02/16 12:54:43 INFO rpc.ClientWorker: 0x7fffffb9 Writing bare RPC Response to satellite.local:715
12/02/16 12:54:43 INFO rpc.ClientWorker: 0x7fffffb9 got request
12/02/16 12:54:43 WARN handlers.OperationRequestHandler: 0x7fffffb9 Error for client /192.168.1.10 and GETATTRResponse
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getObject(FSInfo.java:78)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getUsed(FSInfo.java:63)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:38)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.SpaceUsedHandler.get(SpaceUsedHandler.java:1)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.Attribute.getAttrs(Attribute.java:175)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:54)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.GETATTRHandler.doHandle(GETATTRHandler.java:1)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.handlers.OperationRequestHandler.handle(OperationRequestHandler.java:57)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler$1.run(NFS4Handler.java:148)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler$1.run(NFS4Handler.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:396)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1083)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler.process(NFS4Handler.java:136)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.NFS4Handler.process(NFS4Handler.java:1)
        at com.cloudera.hadoop.hdfs.nfs.rpc.ClientWorker$ClientTask.run(ClientWorker.java:379)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.cloudera.hadoop.hdfs.nfs.nfs4.attrs.FSInfo.getObject(FSInfo.java:76)
        ... 18 more

Caused by: org.apache.hadoop.ipc.RemoteException: org.apache.hadoop.security.AccessControlException: Access denied for user root. Superuser privilege is required
        at org.apache.hadoop.hdfs.server.namenode.PermissionChecker.checkSuperuserPrivilege(PermissionChecker.java:69)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkSuperuserPrivilege(FSNamesystem.java:5196)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getStats(FSNamesystem.java:4061)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.getStats(NameNode.java:853)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:563)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1388)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:1384)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:396)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1083)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:1382)

```
    at org.apache.hadoop.ipc.Client.call(Client.java:1066)
    at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:225)
    at $Proxy1.getStats(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:82)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:59)
    at $Proxy1.getStats(Unknown Source)
    at org.apache.hadoop.hdfs.DFSClient.totalRawUsed(DFSClient.java:1078)
    ... 23 more
```

12/02/16 12:54:43 WARN nfs4.NFS4Handler: 0x7fffffb9 Quitting due to 10006 on GETATTRRequest for root
12/02/16 12:54:43 INFO rpc.ClientWorker: 0x7fffffb9 Writing CompoundResponse to satellite.local:715
12/02/16 12:54:43 INFO rpc.ClientWorker: 0x7fffffb9 Shutdown worker for client satellite.local:715

**Comment by brockn** [comment] 2012-02-16 13:19
What version of hadoop are you using? I think I know whats going on.

**Comment by nickb937** [comment] 2012-02-16 14:40
I'm running version 1.0.0

**Comment by brockn** [comment] 2012-02-16 14:41
That's what I figured. I will see what I can do.

**Comment by brockn** [comment] 2012-02-22 01:01
The issue would 1.0.0 should be fixed but I have not tested it against a cluster. If it's not, please open a separate issue tas this one is supposed to around append.

**Closed as completed by brockn** 2012-02-22 01:01 UTC
